language: python
sudo: required
dist: xenial
python:
  - '3.6'
  - '3.6-dev'
  - '3.7'
  - '3.7-dev'

before_script:
  - sudo apt-get install -y opus-tools

script:
  - python -m unittest discover -s tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
