language: python
sudo: required
dist: xenial
python:
  - '3.6'
  - '3.6-dev'
  - '3.7'
  - '3.7-dev'

install:
  - pip install -r requirements.txt
  - pip install codecov
  - sudo apt-get install -y opus-tools

script:
  - python -m unittest discover -s tests
  - coverage run -m unittest discover tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
